name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  deploy-admin-app:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        env:
          VITE_IS_ADMIN: true
      - run: yarn install
      - run: yarn build
      - run: CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} npx wrangler pages publish --project-name=react-starter
