name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  deploy-admin-app:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      VITE_IS_ADMIN: true
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{secrets.CF_API_TOKEN}}
          command: pages publish dist --project-name=react-starter
